### ISSUE TITLE
Can't install hubot-hipchat, and it points at node-stringprep

### ISSUE THREAD

**Issue by RickCogley** [node-xmpp/node-stringprep#76]
Hi - I'm trying to run ``npm install --save hubot-hipchat`` to add the hipchat adapter to my hubot. This part of stdout: 

~~~
npm ERR! Failed at the node-stringprep@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
~~~

... implies it's a problem with node-stringprep. Please see what I think are the relevant logs in this gist: 

https://gist.github.com/RickCogley/53b601d60dc7e509bc79

A little about my environment: 

Shared server at Webfaction
CentOS release 6.7 (Final) (x86_64 GNU/Linux)
gcc v4.8.1 
node v4.0.0
npm  v3.3.9
used npm config to set python = "/usr/local/bin/python2.7"
exported env var PYTHON=python2.7

I hope that is enough info. Could someone please take a look? 

Kind regards,
Rick

**Comment by sonnyp** [comment]
hubot-hipchat is using an old node-xmpp-client version. I have sent a PR to update it https://github.com/hipchat/hubot-hipchat/pull/261  can you try that?

**Comment by RickCogley** [comment]
@sonnyp thanks so much for doing that PR. I'm new to node, and have just been using it for hubot, so far. By try that, I guess you mean a manual compile of the hubot-hipchat adapter, right? If so, could you kindly point me in the right direction as to how to proceed with that? I'm happy to compile and test, but just a newbie with npm.

**Comment by sonnyp** [comment]
@RickCogley 
```
npm install git+https://github.com/sonnyp/hubot-hipchat.git#update-node-xmpp
```
should do the trick
